PERSON_LIST = "/api/persons"
PERSON_DELETE = "/api/persons/{company_id:uuid}"
PERSON_DETAIL = "/api/persons/{company_id:uuid}"
PERSON_UPDATE = "/api/persons/{company_id:uuid}"
PERSON_CREATE = "/api/persons"
PERSON_CREATE_FROM_URL = "/api/persons/from-url"
PERSON_INDEX = "/api/persons/{company_id:uuid}"
