"""Initial

Revision ID: 6d88b85647c5
Revises:
Create Date: 2025-11-12 17:17:33.336566

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import advanced_alchemy.types.datetime

# revision identifiers, used by Alembic.
revision: str = '6d88b85647c5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_id'), 'catalog', ['id'], unique=True)
    op.create_table('match',
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('system', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("entity_type IN ('topic', 'taxonomy')", name='ck_match_entity_type'),
    sa.CheckConstraint("match_type IN ('exactMatch', 'closeMatch', 'broadMatch', 'narrowMatch', 'relatedMatch')", name='ck_match_type'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_match_confidence'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'system', 'external_id', name='uq_match_entity_system_external')
    )
    op.create_index('ix_match_entity', 'match', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_match_id'), 'match', ['id'], unique=True)
    op.create_index('ix_match_system', 'match', ['system'], unique=False)
    op.create_table('purpose',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purpose_id'), 'purpose', ['id'], unique=True)
    op.create_table('repository',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repository_id'), 'repository', ['id'], unique=True)
    op.create_table('taxonomy',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skos_uri', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxonomy_id'), 'taxonomy', ['id'], unique=True)
    op.create_table('catalog_taxonomies',
    sa.Column('catalog_id', sa.String(length=255), nullable=False),
    sa.Column('taxonomy_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('catalog_id', 'taxonomy_id')
    )
    op.create_index('ix_catalog_taxonomies_catalog', 'catalog_taxonomies', ['catalog_id'], unique=False)
    op.create_index('ix_catalog_taxonomies_taxonomy', 'catalog_taxonomies', ['taxonomy_id'], unique=False)
    op.create_table('document_classification',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('taxonomy_id', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('user_feedback', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='check_confidence_range'),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_classification_lookup', 'document_classification', ['document_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_document_classification_document_id'), 'document_classification', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_classification_id'), 'document_classification', ['id'], unique=True)
    op.create_index(op.f('ix_document_classification_taxonomy_id'), 'document_classification', ['taxonomy_id'], unique=False)
    op.create_table('resource',
    sa.Column('catalog_id', sa.String(length=255), nullable=False),
    sa.Column('repository_id', sa.String(length=255), nullable=True),
    sa.Column('catalog', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=1000), nullable=True),
    sa.Column('repository', sa.String(length=255), nullable=True),
    sa.Column('content_location', sa.String(length=1000), nullable=True),
    sa.Column('format', sa.String(length=100), nullable=True),
    sa.Column('media_type', sa.String(length=100), nullable=True),
    sa.Column('theme', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('creator', sa.String(length=255), nullable=True),
    sa.Column('has_purpose', sa.String(length=255), nullable=True),
    sa.Column('has_use', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('has_resources', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=True),
    sa.Column('note_type', sa.String(length=50), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("(has_resources = '[]' OR resource_type = 'Collection')", name='ck_has_resources_only_for_collections'),
    sa.CheckConstraint("(resource_type != 'Resource' AND repository IS NOT NULL) OR (resource_type = 'Resource')", name='ck_repository_required_for_typed_resources'),
    sa.CheckConstraint("(resource_type = 'Resource' AND location IS NOT NULL) OR (resource_type != 'Resource')", name='ck_location_required_for_base_resource'),
    sa.CheckConstraint("document_type IS NULL OR resource_type = 'Document'", name='ck_document_type_only_for_documents'),
    sa.CheckConstraint("note_type IS NULL OR resource_type = 'Note'", name='ck_note_type_only_for_notes'),
    sa.CheckConstraint("resource_type IN ('Resource', 'Bookmark', 'Collection', 'Document', 'Note')", name='ck_resource_type'),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repository.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_catalog_id', 'resource', ['catalog_id'], unique=False)
    op.create_index('ix_resource_created', 'resource', ['created'], unique=False)
    op.create_index(op.f('ix_resource_id'), 'resource', ['id'], unique=True)
    op.create_index('ix_resource_modified', 'resource', ['modified'], unique=False)
    op.create_index('ix_resource_repository_id', 'resource', ['repository_id'], unique=False)
    op.create_index('ix_resource_type', 'resource', ['resource_type'], unique=False)
    op.create_table('topic',
    sa.Column('taxonomy_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('aliases', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('external_refs', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'active', 'deprecated', 'merged')", name='ck_topic_status'),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomy.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('taxonomy_id', 'slug', name='uq_topic_taxonomy_slug'),
    sa.UniqueConstraint('taxonomy_id', 'title', name='uq_topic_taxonomy_title')
    )
    op.create_index('ix_topic_created_at', 'topic', ['created_at'], unique=False)
    op.create_index(op.f('ix_topic_id'), 'topic', ['id'], unique=True)
    op.create_index('ix_topic_path', 'topic', ['path'], unique=False)
    op.create_index('ix_topic_slug', 'topic', ['slug'], unique=False)
    op.create_index('ix_topic_status', 'topic', ['status'], unique=False)
    op.create_index('ix_topic_taxonomy_id', 'topic', ['taxonomy_id'], unique=False)
    op.create_index('ix_topic_taxonomy_status', 'topic', ['taxonomy_id', 'status'], unique=False)
    op.create_index('ix_topic_title', 'topic', ['title'], unique=False)
    op.create_table('document_topic_assignment',
    sa.Column('classification_id', sa.String(length=255), nullable=False),
    sa.Column('topic_id', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('user_feedback', sa.String(length=20), nullable=True),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='check_assignment_confidence_range'),
    sa.CheckConstraint('rank >= 1', name='check_rank_positive'),
    sa.ForeignKeyConstraint(['classification_id'], ['document_classification.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classification_id', 'topic_id', name='uq_classification_topic')
    )
    op.create_index('idx_topic_lookup', 'document_topic_assignment', ['topic_id', 'confidence'], unique=False)
    op.create_index(op.f('ix_document_topic_assignment_classification_id'), 'document_topic_assignment', ['classification_id'], unique=False)
    op.create_index(op.f('ix_document_topic_assignment_id'), 'document_topic_assignment', ['id'], unique=True)
    op.create_index(op.f('ix_document_topic_assignment_topic_id'), 'document_topic_assignment', ['topic_id'], unique=False)
    op.create_table('resource_related_resources',
    sa.Column('source_resource_id', sa.String(length=255), nullable=False),
    sa.Column('related_resource_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['related_resource_id'], ['resource.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_resource_id'], ['resource.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_resource_id', 'related_resource_id')
    )
    op.create_index('ix_resource_related_related', 'resource_related_resources', ['related_resource_id'], unique=False)
    op.create_index('ix_resource_related_source', 'resource_related_resources', ['source_resource_id'], unique=False)
    op.create_table('resource_related_topics',
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('topic_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resource.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id', 'topic_id')
    )
    op.create_index('ix_resource_topics_resource', 'resource_related_topics', ['resource_id'], unique=False)
    op.create_index('ix_resource_topics_topic', 'resource_related_topics', ['topic_id'], unique=False)
    op.create_table('topic_closure',
    sa.Column('ancestor_id', sa.String(length=255), nullable=False),
    sa.Column('descendant_id', sa.String(length=255), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint('depth >= 0', name='ck_closure_depth'),
    sa.ForeignKeyConstraint(['ancestor_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['descendant_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ancestor_id', 'descendant_id', name='uq_closure_ancestor_descendant')
    )
    op.create_index('ix_closure_ancestor_id', 'topic_closure', ['ancestor_id'], unique=False)
    op.create_index('ix_closure_depth', 'topic_closure', ['depth'], unique=False)
    op.create_index('ix_closure_descendant_id', 'topic_closure', ['descendant_id'], unique=False)
    op.create_index(op.f('ix_topic_closure_id'), 'topic_closure', ['id'], unique=True)
    op.create_table('topic_edge',
    sa.Column('parent_id', sa.String(length=255), nullable=False),
    sa.Column('child_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('broader', 'part_of', 'instance_of', 'related')", name='ck_edge_role'),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_edge_confidence'),
    sa.CheckConstraint('parent_id != child_id', name='ck_edge_no_self_loop'),
    sa.ForeignKeyConstraint(['child_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'child_id', name='uq_edge_parent_child')
    )
    op.create_index('ix_edge_child_id', 'topic_edge', ['child_id'], unique=False)
    op.create_index('ix_edge_parent_id', 'topic_edge', ['parent_id'], unique=False)
    op.create_index('ix_edge_role', 'topic_edge', ['role'], unique=False)
    op.create_index(op.f('ix_topic_edge_id'), 'topic_edge', ['id'], unique=True)
    op.create_table('topic_suggestion',
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('taxonomy_id', sa.String(length=255), nullable=True),
    sa.Column('topic_id', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('metadata_json', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_suggestion_confidence'),
    sa.ForeignKeyConstraint(['taxonomy_id'], ['taxonomy.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('input_hash', 'topic_id', 'model_name', 'model_version', name='uq_suggestion_input_topic_model')
    )
    op.create_index('ix_suggestion_input_hash', 'topic_suggestion', ['input_hash'], unique=False)
    op.create_index('ix_suggestion_taxonomy_id', 'topic_suggestion', ['taxonomy_id'], unique=False)
    op.create_index('ix_suggestion_topic_id', 'topic_suggestion', ['topic_id'], unique=False)
    op.create_index(op.f('ix_topic_suggestion_id'), 'topic_suggestion', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topic_suggestion_id'), table_name='topic_suggestion')
    op.drop_index('ix_suggestion_topic_id', table_name='topic_suggestion')
    op.drop_index('ix_suggestion_taxonomy_id', table_name='topic_suggestion')
    op.drop_index('ix_suggestion_input_hash', table_name='topic_suggestion')
    op.drop_table('topic_suggestion')
    op.drop_index(op.f('ix_topic_edge_id'), table_name='topic_edge')
    op.drop_index('ix_edge_role', table_name='topic_edge')
    op.drop_index('ix_edge_parent_id', table_name='topic_edge')
    op.drop_index('ix_edge_child_id', table_name='topic_edge')
    op.drop_table('topic_edge')
    op.drop_index(op.f('ix_topic_closure_id'), table_name='topic_closure')
    op.drop_index('ix_closure_descendant_id', table_name='topic_closure')
    op.drop_index('ix_closure_depth', table_name='topic_closure')
    op.drop_index('ix_closure_ancestor_id', table_name='topic_closure')
    op.drop_table('topic_closure')
    op.drop_index('ix_resource_topics_topic', table_name='resource_related_topics')
    op.drop_index('ix_resource_topics_resource', table_name='resource_related_topics')
    op.drop_table('resource_related_topics')
    op.drop_index('ix_resource_related_source', table_name='resource_related_resources')
    op.drop_index('ix_resource_related_related', table_name='resource_related_resources')
    op.drop_table('resource_related_resources')
    op.drop_index(op.f('ix_document_topic_assignment_topic_id'), table_name='document_topic_assignment')
    op.drop_index(op.f('ix_document_topic_assignment_id'), table_name='document_topic_assignment')
    op.drop_index(op.f('ix_document_topic_assignment_classification_id'), table_name='document_topic_assignment')
    op.drop_index('idx_topic_lookup', table_name='document_topic_assignment')
    op.drop_table('document_topic_assignment')
    op.drop_index('ix_topic_title', table_name='topic')
    op.drop_index('ix_topic_taxonomy_status', table_name='topic')
    op.drop_index('ix_topic_taxonomy_id', table_name='topic')
    op.drop_index('ix_topic_status', table_name='topic')
    op.drop_index('ix_topic_slug', table_name='topic')
    op.drop_index('ix_topic_path', table_name='topic')
    op.drop_index(op.f('ix_topic_id'), table_name='topic')
    op.drop_index('ix_topic_created_at', table_name='topic')
    op.drop_table('topic')
    op.drop_index('ix_resource_type', table_name='resource')
    op.drop_index('ix_resource_repository_id', table_name='resource')
    op.drop_index('ix_resource_modified', table_name='resource')
    op.drop_index(op.f('ix_resource_id'), table_name='resource')
    op.drop_index('ix_resource_created', table_name='resource')
    op.drop_index('ix_resource_catalog_id', table_name='resource')
    op.drop_table('resource')
    op.drop_index(op.f('ix_document_classification_taxonomy_id'), table_name='document_classification')
    op.drop_index(op.f('ix_document_classification_id'), table_name='document_classification')
    op.drop_index(op.f('ix_document_classification_document_id'), table_name='document_classification')
    op.drop_index('idx_doc_classification_lookup', table_name='document_classification')
    op.drop_table('document_classification')
    op.drop_index('ix_catalog_taxonomies_taxonomy', table_name='catalog_taxonomies')
    op.drop_index('ix_catalog_taxonomies_catalog', table_name='catalog_taxonomies')
    op.drop_table('catalog_taxonomies')
    op.drop_index(op.f('ix_taxonomy_id'), table_name='taxonomy')
    op.drop_table('taxonomy')
    op.drop_index(op.f('ix_repository_id'), table_name='repository')
    op.drop_table('repository')
    op.drop_index(op.f('ix_purpose_id'), table_name='purpose')
    op.drop_table('purpose')
    op.drop_index('ix_match_system', table_name='match')
    op.drop_index(op.f('ix_match_id'), table_name='match')
    op.drop_index('ix_match_entity', table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_catalog_id'), table_name='catalog')
    op.drop_table('catalog')
    # ### end Alembic commands ###
