# Topic and Taxonomy schemas
# Catalog schemas
from ontology.schema.catalog import (
    ApplySuggestionsRequest,
    BookmarkCreate,
    BookmarkResponse,
    CatalogCreate,
    CatalogResponse,
    CatalogUpdate,
    CollectionCreate,
    CollectionResponse,
    DocumentCreate,
    DocumentResponse,
    DocumentUpdate,
    NewTopicCreation,
    NewTopicProposal,
    NoteCreate,
    NoteResponse,
    NoteSuggestionRequest,
    NoteSuggestionResponse,
    NoteUpdate,
    PurposeCreate,
    PurposeResponse,
    RepositoryCreate,
    RepositoryResponse,
    RepositoryUpdate,
    ResourceBase,
    ResourceCreate,
    ResourceResponse,
    ResourceUpdate,
    TopicSuggestionDetail,
)

# Classifier schemas
from ontology.schema.classifier import (
    ClassificationHistoryResponse,
    DocumentClassificationRequest,
    DocumentClassificationResponse,
    FeedbackRequest,
    ParentSuggestion,
    ParentSuggestionRequest,
    TaxonomyClassificationRequest,
    TaxonomyClassificationResponse,
    TaxonomySuggestion,
    TopicSuggestion,
    TopicSuggestionRequest,
    TopicSuggestionResponse,
    TopicSuggestionResult,
)
from ontology.schema.taxonomy import (
    TaxonomyBase,
    TaxonomyCreate,
    TaxonomyListResponse,
    TaxonomyResponse,
    TaxonomyUpdate,
)
from ontology.schema.topic import (
    EdgeRole,
    TopicBase,
    TopicCountsResponse,
    TopicCreate,
    TopicEdgeBase,
    TopicEdgeCreate,
    TopicEdgeResponse,
    TopicListResponse,
    TopicOverview,
    TopicOverviewListResponse,
    TopicRecentListResponse,
    TopicRelationshipRef,
    TopicResponse,
    TopicSearchRequest,
    TopicStatus,
    TopicSummaryResponse,
    TopicUpdate,
)

__all__ = [
    # Taxonomy
    "TaxonomyBase",
    "TaxonomyCreate",
    "TaxonomyUpdate",
    "TaxonomyResponse",
    "TaxonomyListResponse",
    # Topic
    "TopicBase",
    "TopicCreate",
    "TopicUpdate",
    "TopicResponse",
    "TopicListResponse",
    "TopicSearchRequest",
    "TopicRelationshipRef",
    "TopicOverview",
    "TopicOverviewListResponse",
    "TopicEdgeBase",
    "TopicEdgeCreate",
    "TopicEdgeResponse",
    "TopicSummaryResponse",
    "TopicCountsResponse",
    "TopicRecentListResponse",
    "TopicStatus",
    "EdgeRole",
    # Catalog
    "CatalogCreate",
    "CatalogUpdate",
    "CatalogResponse",
    "RepositoryCreate",
    "RepositoryResponse",
    "RepositoryUpdatePurposeCreate",
    "PurposeResponse",
    "ResourceBase",
    "ResourceCreate",
    "ResourceUpdate",
    "ResourceResponse",
    "BookmarkCreate",
    "BookmarkResponse",
    "CollectionCreate",
    "CollectionResponse",
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "NoteCreate",
    "NoteUpdate",
    "NoteResponse",
    "NoteSuggestionRequest",
    "TopicSuggestionDetail",
    "NewTopicProposal",
    "NoteSuggestionResponse",
    "NewTopicCreation",
    "ApplySuggestionsRequest",
    # Classifier
    "ClassificationHistoryResponse",
    "DocumentClassificationRequest",
    "DocumentClassificationResponse",
    "FeedbackRequest",
    "ParentSuggestion",
    "ParentSuggestionRequest",
    "TaxonomyClassificationRequest",
    "TaxonomyClassificationResponse",
    "TaxonomySuggestion",
    "TopicSuggestion",
    "TopicSuggestionRequest",
    "TopicSuggestionResponse",
    "TopicSuggestionResult",
]
